name: Build runner

run-name: Build runner ${{ inputs.gitRef || github.ref }}

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: 'Commit, tag or branch name to build'
        required: true
        type: string
        default: 'main'
  push:
    branches:
      - main

jobs:
  build-and-publish-runner-image:
    name: Build and publish runner image
    uses: alphagov/govuk-infrastructure/.github/workflows/build-and-push-multiarch-image.yml@main
    with:
      dockerfilePath: ./runner.Dockerfile
      imageName: govuk-synthetic-test-app-runner
      gitRef: ${{ inputs.gitRef || github.ref }}
    permissions:
      id-token: write
      contents: read
      packages: write
